import type { Metadata } from "next";

import NavigationUser from "./_ui/NavigationUser";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(single_recruit);

  // let userDetails: any;
  // try {
  //   const response = await instance.get(`/users/${single_recruit}`);
  //   userDetails = response.data;
  // } catch (error: any) {
  //   console.log(error.response.data);
  //   return <p>error</p>;
  // }

  return (
    <div className="flex flex-col flex-1 p-3 w-full h-full ">
      <div className="w-full">
        <NavigationUser />
      </div>
      <div className=" flex-1 w-full flex flex-col gap-3 md:overflow-y-auto ">
        <div className="flex-1 w-full overflow-y-auto">{children}</div>
      </div>
    </div>
  );
}
