import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./Context/AuthContext";
import { getNames } from "country-list";
import Error from "./components/Error";
import { instance } from "@/utils/axiosConfig";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const countries = getNames();
  let job_type = [];
  let department = [];
  let visa_type = [];
  let site_data = {};

  try {
    const resJob = await instance.get(`/job-type?limit=${0}&offset=${0}`);
    job_type = resJob?.data.data ?? [];

    const resDept = await instance.get(`/department?limit=${0}&offset=${0}`);
    department = resDept?.data.data ?? [];

    const resVisa = await instance.get(`/visa-type?limit=${0}&offset=${0}`);
    visa_type = resVisa?.data.data ?? [];

    const siteData = await instance.get(`/site-details`);

    site_data = siteData?.data.data[0] ?? {};
  } catch (e: any) {
    return (
      <html>
        <body className="flex sm:h-screen w-screen overflow-auto">
          <div className="flex-1 flex flex-col bg-blue-900  bg-[url('/bg-image2.jpg')] bg-blend-darken bg-cover  h-full  overflow-auto">
            <Error error={"Something went wrong"} reloadButton={true} />
          </div>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider
          defaultdata={{
            job_type: job_type,
            department: department,
            visa_type: visa_type,
            site_data,
            countries,
          }}
        >
          {job_type && department && visa_type && countries ? (
            children
          ) : (
            <p>Error</p>
          )}
        </AuthProvider>
      </body>
    </html>
  );
}
