export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import Image from "next/image";
import PublicRedirectGuard from "../Context/PublicRedirectGuard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <PublicRedirectGuard>
      <section className="flex sm:h-screen w-screen overflow-auto">
        <div className="flex-1 flex flex-col bg-blue-900  bg-[url('/bg-image2.jpg')] bg-blend-darken bg-cover  h-full  overflow-auto">
          {children}
        </div>
      </section>
    </PublicRedirectGuard>
  );
}
