export const dynamic = "force-dynamic";

import type { Metadata } from "next";

import Logo from "@/components/Logo";
import Nav from "@/components/Nav";
import DashboardHeader from "@/components/DashboardHeader";
import Protected from "../../Context/Protected";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Protected>
      <section className="flex sm:h-screen w-screen overflow-x-auto">
        <div className="hidden  sm:block  h-full overflow-y-auto p-4">
          {/* LOGO  */}
          <Logo />
          {/* MENU  */}
          <Nav />
        </div>
        <div className="flex-1 flex flex-col bg-gray-400/20 h-full  overflow-x-auto">
          <div className="">
            <DashboardHeader />
          </div>
          <div className="flex-1 w-full overflow-x-auto overflow-y-auto">
            {children}
          </div>
        </div>
      </section>
    </Protected>
  );
}
